package com.test.task.exceptions

class UserAlreadyExistException  : ApplicationException("User already exists")
